# https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
# and https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
name: Pull request review (dependabot)

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
    branches:
      - 'dependabot/**'

jobs:
  review-unit-tests:
    name: Review tests (dependabot)
    runs-on: ubuntu-latest

    # Restrict to verified dependabot user when auto update is enabled
    if: github.event.workflow_run.conclusion != 'skipped' && github.actor == 'dependabot[bot]'

    steps:
      - name: Fetch artifact (unit test)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Pull request"
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish results (unit test)
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "**/build/test-results/test/TEST-*.xml"

  review-ktlint:
    name: Review linting (dependabot)
    runs-on: ubuntu-latest

    # Restrict to verified dependabot user when auto update is enabled
    if: github.event.workflow_run.conclusion != 'skipped' && github.actor == 'dependabot[bot]'

    steps:
      - name: Fetch artifact (ktlint)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Pull request"
          run_id: ${{ github.event.workflow_run.id }}

      - uses: reviewdog/action-setup@v1

      - name: Publish results (ktlint)
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_PULL_REQUEST: ${{ github.event.workflow_run.pull_requests[0].number }}
          CI_COMMIT: ${{ github.event.workflow_run.head_sha }}
        run: |
          args=(
            -f=checkstyle
            -diff="git diff"
            -name=ktlint
            -reporter=github-pr-check   # github-pr-review is unsupported in workflow_run
            -filter-mode=nofilter       # Fully supported by github-pr-check
          )
          cat ktlint-results/ktlint-report-in-checkstyle-format.xml | reviewdog "${args[@]}"
